# Product: WDDE Docker
# Description: Dockerfile for building WDDE image
# Author: Benjamin Norman 2023

FROM ubuntu:20.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*



RUN useradd -ms /bin/bash  webDetector

USER webDetector

WORKDIR /home/webDetector

COPY ../ /home/webDetector/

RUN python3 -m pip install -r requirements.txt

CMD [ "python3", "src/main.py" ]